### ISSUE TITLE
[bug] Bud returns "0" exit code when the build errors

### ISSUE THREAD

**Issue by retlehs** [roots/bud#1698]
### Describe the issue

The Bud process does not return the proper exit code when an error occurs

### Expected Behavior

The process should return an exit status that isn't 0

This is critical for app deploys to fail as expected when a build doesn't complete. If a build fails but the deploy still continues, then the app can be deployed and immediately break

(Props to @joshuafredrickson for raising this on the #bud channel in the Roots Discord server)

### Actual Behavior

The process returns with an exit status of 0

### Steps To Reproduce

1. `yarn add @roots/bud-eslint @roots/eslint-config --dev`
1. Drop a `.eslintrc.cjs` in the project
1. Modify `app.js` to produce an error

Example  `.eslintrc.cjs`:

```javascript
module.exports = {
  root: true,
  extends: ['eslint:recommended'],
  rules: {},
}
```

Example `app.js`:

```javascript
var test = 'test';
```

Example simple `test.sh` script to return the code:

```bash
yarn build
echo $?
```

### version

At least 6.3.5 and 6.4.1 are affected

**Comment by kellymears** [comment]
This should be fixed in [v6.4.2](https://bud.js.org/blog/6.4.2) by https://github.com/roots/bud/commit/d9b606e89bd871a0e72859148f9d82c86ceb538f

**Comment by LucasDemea** [comment]
I still get a 0 error code when the build should fail with bud 6.6.9:
![image](https://user-images.githubusercontent.com/22429540/217777891-17ec12cb-804b-4bb9-beac-d1be19a3e126.png)
EDIT: Updating to 6.7.0 fixed it for me

**Comment by LucasDemea** [comment]
Updating to 6.7.0 fixed it for me
